#' Comprehensive Metabolic Pathway Analysis for Single Cell Data
#'
#' This function performs comprehensive differential metabolic pathway analysis
#' between disease and control conditions across all cell types, or compares
#' a specific cell type against all others (edge case analysis).
#'
#' @param seurat_obj A Seurat object containing single cell data with a METABOLISM assay
#'   containing pathway activity scores (typically generated by scMetabolism package)
#' @param celltype_col Character. Column name in metadata containing cell type annotations.
#'   Default: "final.cell.type"
#' @param disease_col Character. Column name in metadata containing disease/condition labels.
#'   Default: "disease.ident". Only used when edge_case = FALSE
#' @param control_label Character. Label for control condition in disease_col.
#'   Default: "CTRL". Used as denominator in fold change calculations
#' @param disease_label Character. Label for disease condition in disease_col.
#'   Default: "PAH". Used as numerator in fold change calculations
#' @param edge_case Logical. If TRUE, performs edge case analysis (target cell type vs all others).
#'   If FALSE, performs standard disease vs control analysis across all cell types.
#'   Default: FALSE
#' @param edge_case_celltype Character. Cell type to compare against all others when edge_case = TRUE.
#'   Must be specified if edge_case = TRUE. Default: NULL
#' @param min_cells Integer. Minimum number of cells required per group for analysis.
#'   Groups with fewer cells are skipped. Default: 10
#' @param test_method Character. Statistical test method. Options: "wilcox", "t.test".
#'   Default: "wilcox"
#' @param logfc_threshold Numeric. Minimum absolute log2 fold change threshold for significance.
#'   Default: 0.1
#' @param create_plots Logical. Whether to create visualization plots. Default: TRUE
#'
#' @return A list containing:
#'   \describe{
#'     \item{results}{List of data.frames containing pathway analysis results for each comparison}
#'     \item{summary}{Data.frame summarizing all comparisons with cell counts and success status}
#'     \item{mode}{Character indicating analysis mode: "disease_vs_control" or "edge_case"}
#'     \item{seurat_obj}{Modified Seurat object with additional metadata columns}
#'   }
#'
#' @details
#' The function operates in two modes:
#'
#' **Standard Mode (edge_case = FALSE):**
#' - Compares disease vs control within each cell type
#' - Formula: log2(disease/control)
#' - Positive log2FC = higher in disease
#' - Automatically handles multiple cell types
#' - Skips comparisons with insufficient cell numbers
#'
#' **Edge Case Mode (edge_case = TRUE):**
#' - Compares specified cell type vs all other cells
#' - Useful for rare or disease-enriched cell types
#' - Formula: log2(target_celltype/all_others)
#'
#' **Statistical Analysis:**
#' - Uses Wilcoxon rank-sum test or t-test
#' - Benjamini-Hochberg FDR correction
#' - Significance: padj < 0.05 AND |log2FC| > logfc_threshold
#'
#' @examples
#' \dontrun{
#' # Load required packages
#' library(Seurat)
#' library(dplyr)
#' library(ggplot2)
#'
#' # Standard analysis: PAH vs CTRL for each cell type
#' standard_results <- analyze_metabolism_comprehensive(
#'   seurat_obj = endothelial_seurat,
#'   celltype_col = "final.cell.type",
#'   disease_col = "disease.ident",
#'   control_label = "CTRL",
#'   disease_label = "PAH",
#'   edge_case = FALSE,
#'   min_cells = 10
#' )
#'
#' # View summary
#' print(standard_results$summary)
#'
#' # Access specific cell type results
#' gcap_results <- standard_results$results[["gCAP"]]
#'
#' # Edge case: Tip cells vs all others
#' tip_results <- analyze_metabolism_comprehensive(
#'   seurat_obj = endothelial_seurat,
#'   edge_case = TRUE,
#'   edge_case_celltype = "Tip.Like.Cells",
#'   min_cells = 10
#' )
#'
#' # Create visualizations
#' volcano_plots <- create_comprehensive_volcano_grid(standard_results)
#' tip_volcano <- create_comprehensive_volcano_grid(tip_results)
#' }
#'
#' @seealso
#' \code{\link{create_comprehensive_volcano_grid}} for visualization functions
#' \code{\link{compare_metabolism_between_groups}} for underlying comparison function
#'
#' @author Sri Harsha Meghadri
#' @export
#' @import Seurat
#' @import dplyr
#' @import ggplot2
#' @importFrom stats wilcox.test t.test p.adjust
analyze_metabolism_comprehensive <- function(seurat_obj,
                                             celltype_col = "final.cell.type",
                                             disease_col = "disease.ident",
                                             control_label = "CTRL",
                                             disease_label = "PAH",
                                             edge_case = FALSE,
                                             edge_case_celltype = NULL,
                                             min_cells = 10,
                                             test_method = "wilcox",
                                             logfc_threshold = 0.1,
                                             create_plots = TRUE) {

  # Required packages check
  required_packages <- c("Seurat", "dplyr", "ggplot2")
  missing_packages <- required_packages[!sapply(required_packages, requireNamespace, quietly = TRUE)]

  if(length(missing_packages) > 0) {
    stop(paste("Required packages not installed:", paste(missing_packages, collapse = ", "),
               "\nInstall with: install.packages(c('", paste(missing_packages, collapse = "', '"), "'))", sep = ""))
  }

  # Load required libraries
  library(Seurat)
  library(dplyr)
  library(ggplot2)

  # Input validation
  if(!inherits(seurat_obj, "Seurat")) {
    stop("seurat_obj must be a Seurat object")
  }

  if(!"METABOLISM" %in% names(seurat_obj@assays)) {
    stop("Seurat object must contain a METABOLISM assay. Run scMetabolism analysis first.")
  }

  if(!celltype_col %in% colnames(seurat_obj@meta.data)) {
    stop(paste("Column", celltype_col, "not found in Seurat object metadata"))
  }

  if(!edge_case && !disease_col %in% colnames(seurat_obj@meta.data)) {
    stop(paste("Column", disease_col, "not found in Seurat object metadata"))
  }

  if(edge_case && is.null(edge_case_celltype)) {
    stop("edge_case_celltype must be specified when edge_case = TRUE")
  }

  if(!test_method %in% c("wilcox", "t.test")) {
    stop("test_method must be either 'wilcox' or 't.test'")
  }

  cat("=== COMPREHENSIVE METABOLISM ANALYSIS ===\n")

  if(edge_case) {
    cat("MODE: Edge case analysis -", edge_case_celltype, "vs All Others\n\n")

    # Validate edge case celltype exists
    if(!edge_case_celltype %in% seurat_obj@meta.data[[celltype_col]]) {
      stop(paste("edge_case_celltype", edge_case_celltype, "not found in", celltype_col))
    }

    # Create binary grouping
    seurat_obj@meta.data$analysis_group <- ifelse(
      seurat_obj@meta.data[[celltype_col]] == edge_case_celltype,
      edge_case_celltype,
      "All_Others"
    )

    # Check cell counts
    group_counts <- table(seurat_obj@meta.data$analysis_group)
    cat("Cell counts:\n")
    print(group_counts)

    if(group_counts[edge_case_celltype] < min_cells) {
      stop(paste("Insufficient target cells:", group_counts[edge_case_celltype],
                 "< required", min_cells))
    }

    # Run comparison (All_Others as control/denominator)
    results <- compare_metabolism_between_groups(
      seurat_obj = seurat_obj,
      group_col = "analysis_group",
      control_group = "All_Others",  # Denominator
      test_groups = edge_case_celltype,
      min_cells = min_cells,
      test_method = test_method,
      logfc_threshold = logfc_threshold
    )

    analysis_summary <- data.frame(
      comparison = paste(edge_case_celltype, "vs All_Others"),
      target_cells = group_counts[edge_case_celltype],
      control_cells = group_counts["All_Others"],
      n_significant = sum(results[[edge_case_celltype]]$significant),
      status = "Success",
      stringsAsFactors = FALSE
    )

    return(list(
      results = results,
      summary = analysis_summary,
      mode = "edge_case",
      seurat_obj = seurat_obj
    ))

  } else {
    cat("MODE: Disease vs Control across all cell types\n")
    cat("Formula: log2(", disease_label, "/", control_label, ") - positive = higher in disease\n\n")

    # Validate disease labels exist
    available_diseases <- unique(seurat_obj@meta.data[[disease_col]])
    if(!control_label %in% available_diseases) {
      stop(paste("control_label", control_label, "not found in", disease_col,
                 ". Available:", paste(available_diseases, collapse = ", ")))
    }
    if(!disease_label %in% available_diseases) {
      stop(paste("disease_label", disease_label, "not found in", disease_col,
                 ". Available:", paste(available_diseases, collapse = ", ")))
    }

    # Get all available cell types
    all_celltypes <- unique(seurat_obj@meta.data[[celltype_col]])
    cat("Found", length(all_celltypes), "cell types:", paste(all_celltypes, collapse = ", "), "\n\n")

    # Create disease_celltype combinations
    seurat_obj@meta.data$disease_celltype <- paste(
      seurat_obj@meta.data[[disease_col]],
      seurat_obj@meta.data[[celltype_col]],
      sep = "_"
    )

    # Check available combinations
    disease_celltype_table <- table(seurat_obj@meta.data$disease_celltype)
    cat("Available disease-celltype combinations:\n")
    print(disease_celltype_table)
    cat("\n")

    # Initialize results storage
    all_results <- list()
    comparison_summary <- data.frame(
      celltype = character(),
      control_cells = integer(),
      disease_cells = integer(),
      status = character(),
      n_significant = integer(),
      stringsAsFactors = FALSE
    )

    # Loop through each cell type
    for(celltype in all_celltypes) {

      cat("Processing cell type:", celltype, "\n")

      control_group <- paste(control_label, celltype, sep = "_")  # CTRL_gCAP (denominator)
      disease_group <- paste(disease_label, celltype, sep = "_")  # PAH_gCAP (numerator)

      # Check if both groups exist and have sufficient cells
      control_count <- sum(seurat_obj@meta.data$disease_celltype == control_group)
      disease_count <- sum(seurat_obj@meta.data$disease_celltype == disease_group)

      cat("  Control cells (denominator):", control_count, "| Disease cells (numerator):", disease_count, "\n")

      if(control_count < min_cells || disease_count < min_cells) {
        cat("  SKIPPED: Insufficient cells (need >=", min_cells, "per group)\n\n")

        comparison_summary <- rbind(comparison_summary, data.frame(
          celltype = celltype,
          control_cells = control_count,
          disease_cells = disease_count,
          status = "Insufficient cells",
          n_significant = 0,
          stringsAsFactors = FALSE
        ))
        next
      }

      # Run comparison for this cell type (CTRL as control/denominator)
      tryCatch({
        celltype_results <- compare_metabolism_between_groups(
          seurat_obj = seurat_obj,
          group_col = "disease_celltype",
          control_group = control_group,  # CTRL as denominator
          test_groups = disease_group,    # PAH as numerator
          min_cells = min_cells,
          test_method = test_method,
          logfc_threshold = logfc_threshold
        )

        if(length(celltype_results) > 0) {
          all_results[[celltype]] <- celltype_results[[disease_group]]
          n_sig <- sum(celltype_results[[disease_group]]$significant)
          cat("  SUCCESS: Found", n_sig, "significant pathways\n\n")

          comparison_summary <- rbind(comparison_summary, data.frame(
            celltype = celltype,
            control_cells = control_count,
            disease_cells = disease_count,
            status = "Success",
            n_significant = n_sig,
            stringsAsFactors = FALSE
          ))
        } else {
          cat("  WARNING: No results returned\n\n")
          comparison_summary <- rbind(comparison_summary, data.frame(
            celltype = celltype,
            control_cells = control_count,
            disease_cells = disease_count,
            status = "No results",
            n_significant = 0,
            stringsAsFactors = FALSE
          ))
        }

      }, error = function(e) {
        cat("  ERROR:", e$message, "\n\n")
        comparison_summary <- rbind(comparison_summary, data.frame(
          celltype = celltype,
          control_cells = control_count,
          disease_cells = disease_count,
          status = paste("Error:", e$message),
          n_significant = 0,
          stringsAsFactors = FALSE
        ))
      })
    }

    # Print summary
    cat("=== ANALYSIS SUMMARY ===\n")
    print(comparison_summary)

    return(list(
      results = all_results,
      summary = comparison_summary,
      mode = "disease_vs_control",
      seurat_obj = seurat_obj
    ))
  }
}

#' Create Comprehensive Volcano Plot Visualizations
#'
#' Creates volcano plots for comprehensive metabolism analysis results.
#' Handles both multi-panel grids for disease vs control analysis and
#' single plots for edge case analysis.
#'
#' @param analysis_results List output from analyze_metabolism_comprehensive()
#' @param ncol Integer. Number of columns for multi-panel layout. Default: 3
#' @param padj_threshold Numeric. Adjusted p-value threshold for significance. Default: 0.05
#' @param logfc_threshold Numeric. Log2 fold change threshold for significance. Default: 0.1
#' @param label_top_n Integer. Number of top pathways to label. Default: 5
#'
#' @return ggplot object (single plot) or grid.arrange object (multi-panel)
#'
#' @examples
#' \dontrun{
#' # After running comprehensive analysis
#' results <- analyze_metabolism_comprehensive(seurat_obj, edge_case = FALSE)
#' volcano_plots <- create_comprehensive_volcano_grid(results)
#'
#' # For edge case analysis
#' tip_results <- analyze_metabolism_comprehensive(seurat_obj, edge_case = TRUE,
#'                                               edge_case_celltype = "Tip.Like.Cells")
#' tip_volcano <- create_comprehensive_volcano_grid(tip_results)
#' }
#'
#' @export
#' @import ggplot2
#' @import gridExtra
#' @importFrom ggrepel geom_text_repel
create_comprehensive_volcano_grid <- function(analysis_results,
                                              ncol = 3,
                                              padj_threshold = 0.05,
                                              logfc_threshold = 0.1,
                                              label_top_n = 5) {

  # Required packages check
  required_packages <- c("ggplot2", "gridExtra", "ggrepel")
  missing_packages <- required_packages[!sapply(required_packages, requireNamespace, quietly = TRUE)]

  if(length(missing_packages) > 0) {
    stop(paste("Required packages not installed:", paste(missing_packages, collapse = ", "),
               "\nInstall with: install.packages(c('", paste(missing_packages, collapse = "', '"), "'))", sep = ""))
  }

  library(ggplot2)
  library(gridExtra)
  library(ggrepel)

  results <- analysis_results$results
  mode <- analysis_results$mode

  if(mode == "edge_case") {
    # Single volcano plot for edge case
    celltype <- names(results)[1]
    data <- results[[celltype]]

    # Add significance
    data$regulation <- "Not Significant"
    data$regulation[data$padj < padj_threshold & data$log2FC > logfc_threshold] <- "Higher in Target"
    data$regulation[data$padj < padj_threshold & data$log2FC < -logfc_threshold] <- "Lower in Target"

    # Select top pathways to label
    sig_data <- data[data$regulation != "Not Significant", ]
    if(nrow(sig_data) > label_top_n) {
      sig_data$rank_score <- -log10(sig_data$padj) * abs(sig_data$log2FC)
      sig_data <- sig_data[order(sig_data$rank_score, decreasing = TRUE), ]
      to_label <- sig_data[1:label_top_n, ]
    } else {
      to_label <- sig_data
    }

    n_up <- sum(data$regulation == "Higher in Target")
    n_down <- sum(data$regulation == "Lower in Target")

    p <- ggplot(data, aes(x = log2FC, y = -log10(padj))) +
      geom_point(aes(color = regulation), size = 2, alpha = 0.7) +
      scale_color_manual(values = c("Higher in Target" = "#E31A1C",
                                    "Lower in Target" = "#1F78B4",
                                    "Not Significant" = "gray70")) +
      geom_hline(yintercept = -log10(padj_threshold), linetype = "dashed", alpha = 0.5) +
      geom_vline(xintercept = c(-logfc_threshold, logfc_threshold), linetype = "dashed", alpha = 0.5) +
      labs(
        title = paste(celltype, "vs All Others"),
        subtitle = paste0("Higher: ", n_up, " | Lower: ", n_down),
        x = "log₂(Fold Change)",
        y = "-log₁₀(Adjusted p-value)"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(size = 14, face = "bold"),
        legend.position = "bottom"
      )

    # Add labels if any significant pathways
    if(nrow(to_label) > 0) {
      p <- p + geom_text_repel(
        data = to_label,
        aes(label = pathway),
        size = 3,
        max.overlaps = 15,
        box.padding = 0.3
      )
    }

    return(p)

  } else {
    # Multi-panel volcano plots for disease vs control
    plot_list <- list()

    for(celltype in names(results)) {
      data <- results[[celltype]]

      # Add significance
      data$regulation <- "Not Significant"
      data$regulation[data$padj < padj_threshold & data$log2FC > logfc_threshold] <- "Higher in Disease"
      data$regulation[data$padj < padj_threshold & data$log2FC < -logfc_threshold] <- "Lower in Disease"

      n_up <- sum(data$regulation == "Higher in Disease")
      n_down <- sum(data$regulation == "Lower in Disease")

      p <- ggplot(data, aes(x = log2FC, y = -log10(padj))) +
        geom_point(aes(color = regulation), size = 1.5, alpha = 0.7) +
        scale_color_manual(values = c("Higher in Disease" = "#E31A1C",
                                      "Lower in Disease" = "#1F78B4",
                                      "Not Significant" = "gray70")) +
        geom_hline(yintercept = -log10(padj_threshold), linetype = "dashed", alpha = 0.5) +
        geom_vline(xintercept = c(-logfc_threshold, logfc_threshold), linetype = "dashed", alpha = 0.5) +
        labs(
          title = celltype,
          subtitle = paste0("↑", n_up, " ↓", n_down),
          x = "log₂(Disease/Control)",
          y = "-log₁₀(p.adj)"
        ) +
        theme_minimal() +
        theme(
          plot.title = element_text(size = 10, face = "bold"),
          plot.subtitle = element_text(size = 8),
          axis.text = element_text(size = 8),
          axis.title = element_text(size = 9),
          legend.position = "none"
        )

      plot_list[[celltype]] <- p
    }

    # Arrange in grid
    do.call(grid.arrange, c(plot_list, ncol = ncol))
  }
}

# ===== PACKAGE REQUIREMENTS =====
#' Required Packages for Comprehensive Metabolism Analysis
#'
#' This function checks and lists all required packages for the metabolism analysis pipeline.
#'
#' @return Character vector of required package names
#' @export
get_required_packages <- function() {
  required_packages <- c(
    "Seurat",           # Single cell analysis
    "dplyr",            # Data manipulation
    "ggplot2",          # Plotting
    "gridExtra",        # Multi-panel plots
    "ggrepel",          # Text repelling for labels
    "ComplexHeatmap",   # Advanced heatmaps (optional)
    "circlize"          # Color mapping (optional)
  )

  cat("Required packages for comprehensive metabolism analysis:\n")
  cat("Essential:", paste(required_packages[1:5], collapse = ", "), "\n")
  cat("Optional:", paste(required_packages[6:7], collapse = ", "), "\n")

  return(required_packages)
}

#' Install Required Packages
#'
#' Convenience function to install all required packages for metabolism analysis.
#'
#' @param include_optional Logical. Whether to install optional packages. Default: TRUE
#' @export
install_required_packages <- function(include_optional = TRUE) {

  essential_packages <- c("Seurat", "dplyr", "ggplot2", "gridExtra", "ggrepel")
  optional_packages <- c("ComplexHeatmap", "circlize")

  packages_to_install <- essential_packages
  if(include_optional) {
    packages_to_install <- c(packages_to_install, optional_packages)
  }

  # Check which packages are missing
  missing_packages <- packages_to_install[!sapply(packages_to_install, requireNamespace, quietly = TRUE)]

  if(length(missing_packages) > 0) {
    cat("Installing missing packages:", paste(missing_packages, collapse = ", "), "\n")

    # Install CRAN packages
    cran_packages <- missing_packages[!missing_packages %in% c("ComplexHeatmap")]
    if(length(cran_packages) > 0) {
      install.packages(cran_packages)
    }

    # Install Bioconductor packages
    bioc_packages <- missing_packages[missing_packages %in% c("ComplexHeatmap")]
    if(length(bioc_packages) > 0) {
      if (!requireNamespace("BiocManager", quietly = TRUE)) {
        install.packages("BiocManager")
      }
      BiocManager::install(bioc_packages)
    }

    cat("Installation complete!\n")
  } else {
    cat("All required packages are already installed.\n")
  }
}
